var protobufjs = require('protobufjs'),
    util = require('util'),
    Transform = require('stream').Transform;

var nameById = {
    0: 'Version',
    1: 'UDPTunnel',
    2: 'Authenticate',
    3: 'Ping',
    4: 'Reject',
    5: 'ServerSync',
    6: 'ChannelRemove',
    7: 'ChannelState',
    8: 'UserRemove',
    9: 'UserState',
    10: 'BanList',
    11: 'TextMessage',
    12: 'PermissionDenied',
    13: 'ACL',
    14: 'QueryUsers',
    15: 'CryptSetup',
    16: 'ContextActionModify',
    17: 'ContextAction',
    18: 'UserList',
    19: 'VoiceTarget',
    20: 'PermissionQuery',
    21: 'CodecVersion',
    22: 'UserStats',
    23: 'RequestBlob',
    24: 'ServerConfig',
    25: 'SuggestConfig'
};
var idByName = {};
for (var id in nameById) {
	idByName[nameById[id]] = id;
}

// Explicitly reading with readFileSync to support brfs
var mumbleProto = Buffer("Ly8gQ29weXJpZ2h0IDIwMDUtMjAxNiBUaGUgTXVtYmxlIERldmVsb3BlcnMuIEFsbCByaWdodHMgcmVzZXJ2ZWQuCi8vIFVzZSBvZiB0aGlzIHNvdXJjZSBjb2RlIGlzIGdvdmVybmVkIGJ5IGEgQlNELXN0eWxlIGxpY2Vuc2UKLy8gdGhhdCBjYW4gYmUgZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZSBhdCB0aGUgcm9vdCBvZiB0aGUKLy8gTXVtYmxlIHNvdXJjZSB0cmVlIG9yIGF0IDxodHRwczovL3d3dy5tdW1ibGUuaW5mby9MSUNFTlNFPi4KCnBhY2thZ2UgTXVtYmxlUHJvdG87CgpvcHRpb24gb3B0aW1pemVfZm9yID0gU1BFRUQ7CgptZXNzYWdlIFZlcnNpb24gewoJLy8gMi1ieXRlIE1ham9yLCAxLWJ5dGUgTWlub3IgYW5kIDEtYnl0ZSBQYXRjaCB2ZXJzaW9uIG51bWJlci4KCW9wdGlvbmFsIHVpbnQzMiB2ZXJzaW9uID0gMTsKCS8vIENsaWVudCByZWxlYXNlIG5hbWUuCglvcHRpb25hbCBzdHJpbmcgcmVsZWFzZSA9IDI7CgkvLyBDbGllbnQgT1MgbmFtZS4KCW9wdGlvbmFsIHN0cmluZyBvcyA9IDM7CgkvLyBDbGllbnQgT1MgdmVyc2lvbi4KCW9wdGlvbmFsIHN0cmluZyBvc192ZXJzaW9uID0gNDsKfQoKLy8gTm90IHVzZWQuIE5vdCBldmVuIGZvciB0dW5uZWxpbmcgVURQIHRocm91Z2ggVENQLgptZXNzYWdlIFVEUFR1bm5lbCB7CgkvLyBOb3QgdXNlZC4KCXJlcXVpcmVkIGJ5dGVzIHBhY2tldCA9IDE7Cn0KCi8vIFVzZWQgYnkgdGhlIGNsaWVudCB0byBzZW5kIHRoZSBhdXRoZW50aWNhdGlvbiBjcmVkZW50aWFscyB0byB0aGUgc2VydmVyLgptZXNzYWdlIEF1dGhlbnRpY2F0ZSB7CgkvLyBVVEYtOCBlbmNvZGVkIHVzZXJuYW1lLgoJb3B0aW9uYWwgc3RyaW5nIHVzZXJuYW1lID0gMTsKCS8vIFNlcnZlciBvciB1c2VyIHBhc3N3b3JkLgoJb3B0aW9uYWwgc3RyaW5nIHBhc3N3b3JkID0gMjsKCS8vIEFkZGl0aW9uYWwgYWNjZXNzIHRva2VucyBmb3Igc2VydmVyIEFDTCBncm91cHMuCglyZXBlYXRlZCBzdHJpbmcgdG9rZW5zID0gMzsKCS8vIEEgbGlzdCBvZiBDRUxUIGJpdHN0cmVhbSB2ZXJzaW9uIGNvbnN0YW50cyBzdXBwb3J0ZWQgYnkgdGhlIGNsaWVudC4KCXJlcGVhdGVkIGludDMyIGNlbHRfdmVyc2lvbnMgPSA0OwoJb3B0aW9uYWwgYm9vbCBvcHVzID0gNSBbZGVmYXVsdCA9IGZhbHNlXTsKfQoKLy8gU2VudCBieSB0aGUgY2xpZW50IHRvIG5vdGlmeSB0aGUgc2VydmVyIHRoYXQgdGhlIGNsaWVudCBpcyBzdGlsbCBhbGl2ZS4KLy8gU2VydmVyIG11c3QgcmVwbHkgdG8gdGhlIHBhY2tldCB3aXRoIHRoZSBzYW1lIHRpbWVzdGFtcCBhbmQgaXRzIG93bgovLyBnb29kL2xhdGUvbG9zdC9yZXN5bmMgbnVtYmVycy4gTm9uZSBvZiB0aGUgZmllbGRzIGlzIHN0cmljdGx5IHJlcXVpcmVkLgptZXNzYWdlIFBpbmcgewoJLy8gQ2xpZW50IHRpbWVzdGFtcC4gU2VydmVyIHNob3VsZCBub3QgYXR0ZW1wdCB0byBkZWNvZGUuCglvcHRpb25hbCB1aW50NjQgdGltZXN0YW1wID0gMTsKCS8vIFRoZSBhbW91bnQgb2YgZ29vZCBwYWNrZXRzIHJlY2VpdmVkLgoJb3B0aW9uYWwgdWludDMyIGdvb2QgPSAyOwoJLy8gVGhlIGFtb3VudCBvZiBsYXRlIHBhY2tldHMgcmVjZWl2ZWQuCglvcHRpb25hbCB1aW50MzIgbGF0ZSA9IDM7CgkvLyBUaGUgYW1vdW50IG9mIHBhY2tldHMgbmV2ZXIgcmVjZWl2ZWQuCglvcHRpb25hbCB1aW50MzIgbG9zdCA9IDQ7CgkvLyBUaGUgYW1vdW50IG9mIG5vbmNlIHJlc3luY3MuCglvcHRpb25hbCB1aW50MzIgcmVzeW5jID0gNTsKCS8vIFRoZSB0b3RhbCBhbW91bnQgb2YgVURQIHBhY2tldHMgcmVjZWl2ZWQuCglvcHRpb25hbCB1aW50MzIgdWRwX3BhY2tldHMgPSA2OwoJLy8gVGhlIHRvdGFsIGFtb3VudCBvZiBUQ1AgcGFja2V0cyByZWNlaXZlZC4KCW9wdGlvbmFsIHVpbnQzMiB0Y3BfcGFja2V0cyA9IDc7CgkvLyBVRFAgcGluZyBhdmVyYWdlLgoJb3B0aW9uYWwgZmxvYXQgdWRwX3BpbmdfYXZnID0gODsKCS8vIFVEUCBwaW5nIHZhcmlhbmNlLgoJb3B0aW9uYWwgZmxvYXQgdWRwX3BpbmdfdmFyID0gOTsKCS8vIFRDUCBwaW5nIGF2ZXJhZ2UuCglvcHRpb25hbCBmbG9hdCB0Y3BfcGluZ19hdmcgPSAxMDsKCS8vIFRDUCBwaW5nIHZhcmlhbmNlLgoJb3B0aW9uYWwgZmxvYXQgdGNwX3BpbmdfdmFyID0gMTE7Cn0KCi8vIFNlbnQgYnkgdGhlIHNlcnZlciB3aGVuIGl0IHJlamVjdHMgdGhlIHVzZXIgY29ubmVjdGlvbi4KbWVzc2FnZSBSZWplY3QgewoJZW51bSBSZWplY3RUeXBlIHsKCQkvLyBUaGUgcmVqZWN0aW9uIHJlYXNvbiBpcyB1bmtub3duIChkZXRhaWxzIHNob3VsZCBiZSBhdmFpbGFibGUKCQkvLyBpbiBSZWplY3QucmVhc29uKS4KCQlOb25lID0gMDsKCQkvLyBUaGUgY2xpZW50IGF0dGVtcHRlZCB0byBjb25uZWN0IHdpdGggYW4gaW5jb21wYXRpYmxlIHZlcnNpb24uCgkJV3JvbmdWZXJzaW9uID0gMTsKCQkvLyBUaGUgdXNlciBuYW1lIHN1cHBsaWVkIGJ5IHRoZSBjbGllbnQgd2FzIGludmFsaWQuCgkJSW52YWxpZFVzZXJuYW1lID0gMjsKCQkvLyBUaGUgY2xpZW50IGF0dGVtcHRlZCB0byBhdXRoZW50aWNhdGUgYXMgYSB1c2VyIHdpdGggYSBwYXNzd29yZCBidXQgaXQKCQkvLyB3YXMgd3JvbmcuCgkJV3JvbmdVc2VyUFcgPSAzOwoJCS8vIFRoZSBjbGllbnQgYXR0ZW1wdGVkIHRvIGNvbm5lY3QgdG8gYSBwYXNzd29yZGVkIHNlcnZlciBidXQgdGhlIHBhc3N3b3JkCgkJLy8gd2FzIHdyb25nLgoJCVdyb25nU2VydmVyUFcgPSA0OwoJCS8vIFN1cHBsaWVkIHVzZXJuYW1lIGlzIGFscmVhZHkgaW4gdXNlLgoJCVVzZXJuYW1lSW5Vc2UgPSA1OwoJCS8vIFNlcnZlciBpcyBjdXJyZW50bHkgZnVsbCBhbmQgY2Fubm90IGFjY2VwdCBtb3JlIHVzZXJzLgoJCVNlcnZlckZ1bGwgPSA2OwoJCS8vIFRoZSB1c2VyIGRpZCBub3QgcHJvdmlkZSBhIGNlcnRpZmljYXRlIGJ1dCBvbmUgaXMgcmVxdWlyZWQuCgkJTm9DZXJ0aWZpY2F0ZSA9IDc7CgkJQXV0aGVudGljYXRvckZhaWwgPSA4OwoJfQoJLy8gUmVqZWN0aW9uIHR5cGUuCglvcHRpb25hbCBSZWplY3RUeXBlIHR5cGUgPSAxOwoJLy8gSHVtYW4gcmVhZGFibGUgcmVqZWN0aW9uIHJlYXNvbi4KCW9wdGlvbmFsIHN0cmluZyByZWFzb24gPSAyOwp9CgovLyBTZXJ2ZXJTeW5jIG1lc3NhZ2UgaXMgc2VudCBieSB0aGUgc2VydmVyIHdoZW4gaXQgaGFzIGF1dGhlbnRpY2F0ZWQgdGhlIHVzZXIKLy8gYW5kIGZpbmlzaGVkIHN5bmNocm9uaXppbmcgdGhlIHNlcnZlciBzdGF0ZS4KbWVzc2FnZSBTZXJ2ZXJTeW5jIHsKCS8vIFRoZSBzZXNzaW9uIG9mIHRoZSBjdXJyZW50IHVzZXIuCglvcHRpb25hbCB1aW50MzIgc2Vzc2lvbiA9IDE7CgkvLyBNYXhpbXVtIGJhbmR3aWR0aCB0aGF0IHRoZSB1c2VyIHNob3VsZCB1c2UuCglvcHRpb25hbCB1aW50MzIgbWF4X2JhbmR3aWR0aCA9IDI7CgkvLyBTZXJ2ZXIgd2VsY29tZSB0ZXh0LgoJb3B0aW9uYWwgc3RyaW5nIHdlbGNvbWVfdGV4dCA9IDM7CgkvLyBDdXJyZW50IHVzZXIgcGVybWlzc2lvbnMgaW4gdGhlIHJvb3QgY2hhbm5lbC4KCW9wdGlvbmFsIHVpbnQ2NCBwZXJtaXNzaW9ucyA9IDQ7Cn0KCi8vIFNlbnQgYnkgdGhlIGNsaWVudCB3aGVuIGl0IHdhbnRzIGEgY2hhbm5lbCByZW1vdmVkLiBTZW50IGJ5IHRoZSBzZXJ2ZXIgd2hlbgovLyBhIGNoYW5uZWwgaGFzIGJlZW4gcmVtb3ZlZCBhbmQgY2xpZW50cyBzaG91bGQgYmUgbm90aWZpZWQuCm1lc3NhZ2UgQ2hhbm5lbFJlbW92ZSB7CglyZXF1aXJlZCB1aW50MzIgY2hhbm5lbF9pZCA9IDE7Cn0KCi8vIFVzZWQgdG8gY29tbXVuaWNhdGUgY2hhbm5lbCBwcm9wZXJ0aWVzIGJldHdlZW4gdGhlIGNsaWVudCBhbmQgdGhlIHNlcnZlci4KLy8gU2VudCBieSB0aGUgc2VydmVyIGR1cmluZyB0aGUgbG9naW4gcHJvY2VzcyBvciB3aGVuIGNoYW5uZWwgcHJvcGVydGllcyBhcmUKLy8gdXBkYXRlZC4gQ2xpZW50IG1heSB1c2UgdGhpcyBtZXNzYWdlIHRvIHVwZGF0ZSBzYWlkIGNoYW5uZWwgcHJvcGVydGllcy4KbWVzc2FnZSBDaGFubmVsU3RhdGUgewoJLy8gVW5pcXVlIElEIGZvciB0aGUgY2hhbm5lbCB3aXRoaW4gdGhlIHNlcnZlci4KCW9wdGlvbmFsIHVpbnQzMiBjaGFubmVsX2lkID0gMTsKCS8vIGNoYW5uZWxfaWQgb2YgdGhlIHBhcmVudCBjaGFubmVsLgoJb3B0aW9uYWwgdWludDMyIHBhcmVudCA9IDI7CgkvLyBVVEYtOCBlbmNvZGVkIGNoYW5uZWwgbmFtZS4KCW9wdGlvbmFsIHN0cmluZyBuYW1lID0gMzsKCS8vIEEgY29sbGVjdGlvbiBvZiBjaGFubmVsIGlkIHZhbHVlcyBvZiB0aGUgbGlua2VkIGNoYW5uZWxzLiBBYnNlbnQgZHVyaW5nCgkvLyB0aGUgZmlyc3QgY2hhbm5lbCBsaXN0aW5nLgoJcmVwZWF0ZWQgdWludDMyIGxpbmtzID0gNDsKCS8vIFVURi04IGVuY29kZWQgY2hhbm5lbCBkZXNjcmlwdGlvbi4gT25seSBpZiB0aGUgZGVzY3JpcHRpb24gaXMgbGVzcyB0aGFuCgkvLyAxMjggYnl0ZXMKCW9wdGlvbmFsIHN0cmluZyBkZXNjcmlwdGlvbiA9IDU7CgkvLyBBIGNvbGxlY3Rpb24gb2YgY2hhbm5lbF9pZCB2YWx1ZXMgdGhhdCBzaG91bGQgYmUgYWRkZWQgdG8gbGlua3MuCglyZXBlYXRlZCB1aW50MzIgbGlua3NfYWRkID0gNjsKCS8vIEEgY29sbGVjdGlvbiBvZiBjaGFubmVsX2lkIHZhbHVlcyB0aGF0IHNob3VsZCBiZSByZW1vdmVkIGZyb20gbGlua3MuCglyZXBlYXRlZCB1aW50MzIgbGlua3NfcmVtb3ZlID0gNzsKCS8vIFRydWUgaWYgdGhlIGNoYW5uZWwgaXMgdGVtcG9yYXJ5LgoJb3B0aW9uYWwgYm9vbCB0ZW1wb3JhcnkgPSA4IFtkZWZhdWx0ID0gZmFsc2VdOwoJLy8gUG9zaXRpb24gd2VpZ2h0IHRvIHR3ZWFrIHRoZSBjaGFubmVsIHBvc2l0aW9uIGluIHRoZSBjaGFubmVsIGxpc3QuCglvcHRpb25hbCBpbnQzMiBwb3NpdGlvbiA9IDkgW2RlZmF1bHQgPSAwXTsKCS8vIFNIQTEgaGFzaCBvZiB0aGUgZGVzY3JpcHRpb24gaWYgdGhlIGRlc2NyaXB0aW9uIGlzIDEyOCBieXRlcyBvciBtb3JlLgoJb3B0aW9uYWwgYnl0ZXMgZGVzY3JpcHRpb25faGFzaCA9IDEwOwoJLy8gTWF4aW11bSBudW1iZXIgb2YgdXNlcnMgYWxsb3dlZCBpbiB0aGUgY2hhbm5lbC4gSWYgdGhpcyB2YWx1ZSBpcyB6ZXJvLAoJLy8gdGhlIG1heGltdW0gbnVtYmVyIG9mIHVzZXJzIGFsbG93ZWQgaW4gdGhlIGNoYW5uZWwgaXMgZ2l2ZW4gYnkgdGhlCgkvLyBzZXJ2ZXIncyAidXNlcnNwZXJjaGFubmVsIiBzZXR0aW5nLgoJb3B0aW9uYWwgdWludDMyIG1heF91c2VycyA9IDExOwp9CgovLyBVc2VkIHRvIGNvbW11bmljYXRlIHVzZXIgbGVhdmluZyBvciBiZWluZyBraWNrZWQuIE1heSBiZSBzZW50IGJ5IHRoZSBjbGllbnQKLy8gd2hlbiBpdCBhdHRlbXB0cyB0byBraWNrIGEgdXNlci4gU2VudCBieSB0aGUgc2VydmVyIHdoZW4gaXQgaW5mb3JtcyB0aGUKLy8gY2xpZW50cyB0aGF0IGEgdXNlciBpcyBub3QgcHJlc2VudCBhbnltb3JlLgptZXNzYWdlIFVzZXJSZW1vdmUgewoJLy8gVGhlIHVzZXIgd2hvIGlzIGJlaW5nIGtpY2tlZCwgaWRlbnRpZmllZCBieSB0aGVpciBzZXNzaW9uLCBub3QgcHJlc2VudAoJLy8gd2hlbiBubyBvbmUgaXMgYmVpbmcga2lja2VkLgoJcmVxdWlyZWQgdWludDMyIHNlc3Npb24gPSAxOwoJLy8gVGhlIHVzZXIgd2hvIGluaXRpYXRlZCB0aGUgcmVtb3ZhbC4gRWl0aGVyIHRoZSB1c2VyIHdobyBwZXJmb3JtcyB0aGUga2ljawoJLy8gb3IgdGhlIHVzZXIgd2hvIGlzIGN1cnJlbnRseSBsZWF2aW5nLgoJb3B0aW9uYWwgdWludDMyIGFjdG9yID0gMjsKCS8vIFJlYXNvbiBmb3IgdGhlIGtpY2ssIHN0b3JlZCBhcyB0aGUgYmFuIHJlYXNvbiBpZiB0aGUgdXNlciBpcyBiYW5uZWQuCglvcHRpb25hbCBzdHJpbmcgcmVhc29uID0gMzsKCS8vIFRydWUgaWYgdGhlIGtpY2sgc2hvdWxkIHJlc3VsdCBpbiBhIGJhbi4KCW9wdGlvbmFsIGJvb2wgYmFuID0gNDsKfQoKLy8gU2VudCBieSB0aGUgc2VydmVyIHdoZW4gaXQgY29tbXVuaWNhdGVzIG5ldyBhbmQgY2hhbmdlZCB1c2VycyB0byBjbGllbnQuCi8vIEZpcnN0IHNlZW4gZHVyaW5nIGxvZ2luIHByb2NlZHVyZS4gTWF5IGJlIHNlbnQgYnkgdGhlIGNsaWVudCB3aGVuIGl0IHdpc2hlcwovLyB0byBhbHRlciBpdHMgc3RhdGUuCm1lc3NhZ2UgVXNlclN0YXRlIHsKCS8vIFVuaXF1ZSB1c2VyIHNlc3Npb24gSUQgb2YgdGhlIHVzZXIgd2hvc2Ugc3RhdGUgdGhpcyBpcywgbWF5IGNoYW5nZSBvbgoJLy8gcmVjb25uZWN0LgoJb3B0aW9uYWwgdWludDMyIHNlc3Npb24gPSAxOwoJLy8gVGhlIHNlc3Npb24gb2YgdGhlIHVzZXIgd2hvIGlzIHVwZGF0aW5nIHRoaXMgdXNlci4KCW9wdGlvbmFsIHVpbnQzMiBhY3RvciA9IDI7CgkvLyBVc2VyIG5hbWUsIFVURi04IGVuY29kZWQuCglvcHRpb25hbCBzdHJpbmcgbmFtZSA9IDM7CgkvLyBSZWdpc3RlcmVkIHVzZXIgSUQgaWYgdGhlIHVzZXIgaXMgcmVnaXN0ZXJlZC4KCW9wdGlvbmFsIHVpbnQzMiB1c2VyX2lkID0gNDsKCS8vIENoYW5uZWwgb24gd2hpY2ggdGhlIHVzZXIgaXMuCglvcHRpb25hbCB1aW50MzIgY2hhbm5lbF9pZCA9IDU7CgkvLyBUcnVlIGlmIHRoZSB1c2VyIGlzIG11dGVkIGJ5IGFkbWluLgoJb3B0aW9uYWwgYm9vbCBtdXRlID0gNjsKCS8vIFRydWUgaWYgdGhlIHVzZXIgaXMgZGVhZmVuZWQgYnkgYWRtaW4uCglvcHRpb25hbCBib29sIGRlYWYgPSA3OwoJLy8gVHJ1ZSBpZiB0aGUgdXNlciBoYXMgYmVlbiBzdXBwcmVzc2VkIGZyb20gdGFsa2luZyBieSBhIHJlYXNvbiBvdGhlciB0aGFuCgkvLyBiZWluZyBtdXRlZC4KCW9wdGlvbmFsIGJvb2wgc3VwcHJlc3MgPSA4OwoJLy8gVHJ1ZSBpZiB0aGUgdXNlciBoYXMgbXV0ZWQgc2VsZi4KCW9wdGlvbmFsIGJvb2wgc2VsZl9tdXRlID0gOTsKCS8vIFRydWUgaWYgdGhlIHVzZXIgaGFzIGRlYWZlbmVkIHNlbGYuCglvcHRpb25hbCBib29sIHNlbGZfZGVhZiA9IDEwOwoJLy8gVXNlciBpbWFnZSBpZiBpdCBpcyBsZXNzIHRoYW4gMTI4IGJ5dGVzLgoJb3B0aW9uYWwgYnl0ZXMgdGV4dHVyZSA9IDExOwoJLy8gVGhlIHBvc2l0aW9uYWwgYXVkaW8gcGx1Z2luIGlkZW50aWZpZXIuCgkvLyBQb3NpdGlvbmFsIGF1ZGlvIGluZm9ybWF0aW9uIGlzIG9ubHkgc2VudCB0byB1c2VycyB3aG8gc2hhcmUKCS8vIGlkZW50aWNhbCBwbHVnaW4gY29udGV4dHMuCgkvLwoJLy8gVGhpcyB2YWx1ZSBpcyBub3QgdHJhc21pdHRlZCB0byBjbGllbnRzLgoJb3B0aW9uYWwgYnl0ZXMgcGx1Z2luX2NvbnRleHQgPSAxMjsKCS8vIFRoZSB1c2VyJ3MgcGx1Z2luLXNwZWNpZmljIGlkZW50aXR5LgoJLy8gVGhpcyB2YWx1ZSBpcyBub3QgdHJhbnNtaXR0ZWQgdG8gY2xpZW50cy4KCW9wdGlvbmFsIHN0cmluZyBwbHVnaW5faWRlbnRpdHkgPSAxMzsKCS8vIFVzZXIgY29tbWVudCBpZiBpdCBpcyBsZXNzIHRoYW4gMTI4IGJ5dGVzLgoJb3B0aW9uYWwgc3RyaW5nIGNvbW1lbnQgPSAxNDsKCS8vIFRoZSBoYXNoIG9mIHRoZSB1c2VyIGNlcnRpZmljYXRlLgoJb3B0aW9uYWwgc3RyaW5nIGhhc2ggPSAxNTsKCS8vIFNIQTEgaGFzaCBvZiB0aGUgdXNlciBjb21tZW50IGlmIGl0IDEyOCBieXRlcyBvciBtb3JlLgoJb3B0aW9uYWwgYnl0ZXMgY29tbWVudF9oYXNoID0gMTY7CgkvLyBTSEExIGhhc2ggb2YgdGhlIHVzZXIgcGljdHVyZSBpZiBpdCAxMjggYnl0ZXMgb3IgbW9yZS4KCW9wdGlvbmFsIGJ5dGVzIHRleHR1cmVfaGFzaCA9IDE3OwoJLy8gVHJ1ZSBpZiB0aGUgdXNlciBpcyBhIHByaW9yaXR5IHNwZWFrZXIuCglvcHRpb25hbCBib29sIHByaW9yaXR5X3NwZWFrZXIgPSAxODsKCS8vIFRydWUgaWYgdGhlIHVzZXIgaXMgY3VycmVudGx5IHJlY29yZGluZy4KCW9wdGlvbmFsIGJvb2wgcmVjb3JkaW5nID0gMTk7Cn0KCi8vIFJlbGF5cyBpbmZvcm1hdGlvbiBvbiB0aGUgYmFucy4gVGhlIGNsaWVudCBtYXkgc2VuZCB0aGUgQmFuTGlzdCBtZXNzYWdlIHRvCi8vIGVpdGhlciBtb2RpZnkgdGhlIGxpc3Qgb2YgYmFucyBvciBxdWVyeSB0aGVtIGZyb20gdGhlIHNlcnZlci4gVGhlIHNlcnZlcgovLyBzZW5kcyB0aGlzIGxpc3Qgb25seSBhZnRlciBhIGNsaWVudCBxdWVyaWVzIGZvciBpdC4KbWVzc2FnZSBCYW5MaXN0IHsKCW1lc3NhZ2UgQmFuRW50cnkgewoJCS8vIEJhbm5lZCBJUCBhZGRyZXNzLgoJCXJlcXVpcmVkIGJ5dGVzIGFkZHJlc3MgPSAxOwoJCS8vIFRoZSBsZW5ndGggb2YgdGhlIHN1Ym5ldCBtYXNrIGZvciB0aGUgYmFuLgoJCXJlcXVpcmVkIHVpbnQzMiBtYXNrID0gMjsKCQkvLyBVc2VyIG5hbWUgZm9yIGlkZW50aWZpY2F0aW9uIHB1cnBvc2VzIChkb2VzIG5vdCBhZmZlY3QgdGhlIGJhbikuCgkJb3B0aW9uYWwgc3RyaW5nIG5hbWUgPSAzOwoJCS8vIFRoZSBjZXJ0aWZpY2F0ZSBoYXNoIG9mIHRoZSBiYW5uZWQgdXNlci4KCQlvcHRpb25hbCBzdHJpbmcgaGFzaCA9IDQ7CgkJLy8gUmVhc29uIGZvciB0aGUgYmFuIChkb2VzIG5vdCBhZmZlY3QgdGhlIGJhbikuCgkJb3B0aW9uYWwgc3RyaW5nIHJlYXNvbiA9IDU7CgkJLy8gQmFuIHN0YXJ0IHRpbWUuCgkJb3B0aW9uYWwgc3RyaW5nIHN0YXJ0ID0gNjsKCQkvLyBCYW4gZHVyYXRpb24gaW4gc2Vjb25kcy4KCQlvcHRpb25hbCB1aW50MzIgZHVyYXRpb24gPSA3OwoJfQoJLy8gTGlzdCBvZiBiYW4gZW50cmllcyBjdXJyZW50bHkgaW4gcGxhY2UuCglyZXBlYXRlZCBCYW5FbnRyeSBiYW5zID0gMTsKCS8vIFRydWUgaWYgdGhlIHNlcnZlciBzaG91bGQgcmV0dXJuIHRoZSBsaXN0LCBmYWxzZSBpZiBpdCBzaG91bGQgcmVwbGFjZSBvbGQKCS8vIGJhbiBsaXN0IHdpdGggdGhlIG9uZSBwcm92aWRlZC4KCW9wdGlvbmFsIGJvb2wgcXVlcnkgPSAyIFtkZWZhdWx0ID0gZmFsc2VdOwp9CgovLyBVc2VkIHRvIHNlbmQgYW5kIGJyb2FkY2FzdCB0ZXh0IG1lc3NhZ2VzLgptZXNzYWdlIFRleHRNZXNzYWdlIHsKCS8vIFRoZSBtZXNzYWdlIHNlbmRlciwgaWRlbnRpZmllZCBieSBpdHMgc2Vzc2lvbi4KCW9wdGlvbmFsIHVpbnQzMiBhY3RvciA9IDE7CgkvLyBUYXJnZXQgdXNlcnMgZm9yIHRoZSBtZXNzYWdlLCBpZGVudGlmaWVkIGJ5IHRoZWlyIHNlc3Npb24uCglyZXBlYXRlZCB1aW50MzIgc2Vzc2lvbiA9IDI7CgkvLyBUaGUgY2hhbm5lbHMgdG8gd2hpY2ggdGhlIG1lc3NhZ2UgaXMgc2VudCwgaWRlbnRpZmllZCBieSB0aGVpcgoJLy8gY2hhbm5lbF9pZHMuCglyZXBlYXRlZCB1aW50MzIgY2hhbm5lbF9pZCA9IDM7CgkvLyBUaGUgcm9vdCBjaGFubmVscyB3aGVuIHNlbmRpbmcgbWVzc2FnZSByZWN1cnNpdmVseSB0byBzZXZlcmFsIGNoYW5uZWxzLAoJLy8gaWRlbnRpZmllZCBieSB0aGVpciBjaGFubmVsX2lkcy4KCXJlcGVhdGVkIHVpbnQzMiB0cmVlX2lkID0gNDsKCS8vIFRoZSBVVEYtOCBlbmNvZGVkIG1lc3NhZ2UuIE1heSBiZSBIVE1MIGlmIHRoZSBzZXJ2ZXIgYWxsb3dzLgoJcmVxdWlyZWQgc3RyaW5nIG1lc3NhZ2UgPSA1Owp9CgptZXNzYWdlIFBlcm1pc3Npb25EZW5pZWQgewoJZW51bSBEZW55VHlwZSB7CgkJLy8gT3BlcmF0aW9uIGRlbmllZCBmb3Igb3RoZXIgcmVhc29uLCBzZWUgcmVhc29uIGZpZWxkLgoJCVRleHQgPSAwOwoJCS8vIFBlcm1pc3Npb25zIHdlcmUgZGVuaWVkLgoJCVBlcm1pc3Npb24gPSAxOwoJCS8vIENhbm5vdCBtb2RpZnkgU3VwZXJVc2VyLgoJCVN1cGVyVXNlciA9IDI7CgkJLy8gSW52YWxpZCBjaGFubmVsIG5hbWUuCgkJQ2hhbm5lbE5hbWUgPSAzOwoJCS8vIFRleHQgbWVzc2FnZSB0b28gbG9uZy4KCQlUZXh0VG9vTG9uZyA9IDQ7CgkJLy8gVGhlIGZsdXggY2FwYWNpdG9yIHdhcyBzcGVsbGVkIHdyb25nLgoJCUg5SyA9IDU7CgkJLy8gT3BlcmF0aW9uIG5vdCBwZXJtaXR0ZWQgaW4gdGVtcG9yYXJ5IGNoYW5uZWwuCgkJVGVtcG9yYXJ5Q2hhbm5lbCA9IDY7CgkJLy8gT3BlcmF0aW9uIHJlcXVpcmVzIGNlcnRpZmljYXRlLgoJCU1pc3NpbmdDZXJ0aWZpY2F0ZSA9IDc7CgkJLy8gSW52YWxpZCB1c2VybmFtZS4KCQlVc2VyTmFtZSA9IDg7CgkJLy8gQ2hhbm5lbCBpcyBmdWxsLgoJCUNoYW5uZWxGdWxsID0gOTsKCQlOZXN0aW5nTGltaXQgPSAxMDsKCX0KCS8vIFRoZSBkZW5pZWQgcGVybWlzc2lvbiB3aGVuIHR5cGUgaXMgUGVybWlzc2lvbi4KCW9wdGlvbmFsIHVpbnQzMiBwZXJtaXNzaW9uID0gMTsKCS8vIGNoYW5uZWxfaWQgZm9yIHRoZSBjaGFubmVsIHdoZXJlIHRoZSBwZXJtaXNzaW9uIHdhcyBkZW5pZWQgd2hlbiB0eXBlIGlzCgkvLyBQZXJtaXNzaW9uLgoJb3B0aW9uYWwgdWludDMyIGNoYW5uZWxfaWQgPSAyOwoJLy8gVGhlIHVzZXIgd2hvIHdhcyBkZW5pZWQgcGVybWlzc2lvbnMsIGlkZW50aWZpZWQgYnkgc2Vzc2lvbi4KCW9wdGlvbmFsIHVpbnQzMiBzZXNzaW9uID0gMzsKCS8vIFRleHR1YWwgcmVhc29uIGZvciB0aGUgZGVuaWFsLgoJb3B0aW9uYWwgc3RyaW5nIHJlYXNvbiA9IDQ7CgkvLyBUeXBlIG9mIHRoZSBkZW5pYWwuCglvcHRpb25hbCBEZW55VHlwZSB0eXBlID0gNTsKCS8vIFRoZSBuYW1lIHRoYXQgaXMgaW52YWxpZCB3aGVuIHR5cGUgaXMgVXNlck5hbWUuCglvcHRpb25hbCBzdHJpbmcgbmFtZSA9IDY7Cn0KCm1lc3NhZ2UgQUNMIHsKCW1lc3NhZ2UgQ2hhbkdyb3VwIHsKCQkvLyBOYW1lIG9mIHRoZSBjaGFubmVsIGdyb3VwLCBVVEYtOCBlbmNvZGVkLgoJCXJlcXVpcmVkIHN0cmluZyBuYW1lID0gMTsKCQkvLyBUcnVlIGlmIHRoZSBncm91cCBoYXMgYmVlbiBpbmhlcml0ZWQgZnJvbSB0aGUgcGFyZW50IChSZWFkIG9ubHkpLgoJCW9wdGlvbmFsIGJvb2wgaW5oZXJpdGVkID0gMiBbZGVmYXVsdCA9IHRydWVdOwoJCS8vIFRydWUgaWYgdGhlIGdyb3VwIG1lbWJlcnMgYXJlIGluaGVyaXRlZC4KCQlvcHRpb25hbCBib29sIGluaGVyaXQgPSAzIFtkZWZhdWx0ID0gdHJ1ZV07CgkJLy8gVHJ1ZSBpZiB0aGUgZ3JvdXAgY2FuIGJlIGluaGVyaXRlZCBieSBzdWIgY2hhbm5lbHMuCgkJb3B0aW9uYWwgYm9vbCBpbmhlcml0YWJsZSA9IDQgW2RlZmF1bHQgPSB0cnVlXTsKCQkvLyBVc2VycyBleHBsaWNpdGx5IGluY2x1ZGVkIGluIHRoaXMgZ3JvdXAsIGlkZW50aWZpZWQgYnkgdXNlcl9pZC4KCQlyZXBlYXRlZCB1aW50MzIgYWRkID0gNTsKCQkvLyBVc2VycyBleHBsaWNpdGx5IHJlbW92ZWQgZnJvbSB0aGlzIGdyb3VwIGluIHRoaXMgY2hhbm5lbCBpZiB0aGUgZ3JvdXAKCQkvLyBoYXMgYmVlbiBpbmhlcml0ZWQsIGlkZW50aWZpZWQgYnkgdXNlcl9pZC4KCQlyZXBlYXRlZCB1aW50MzIgcmVtb3ZlID0gNjsKCQkvLyBVc2VycyBpbmhlcml0ZWQsIGlkZW50aWZpZWQgYnkgdXNlcl9pZC4KCQlyZXBlYXRlZCB1aW50MzIgaW5oZXJpdGVkX21lbWJlcnMgPSA3OwoJfQoJbWVzc2FnZSBDaGFuQUNMIHsKCQkvLyBUcnVlIGlmIHRoaXMgQUNMIGFwcGxpZXMgdG8gdGhlIGN1cnJlbnQgY2hhbm5lbC4KCQlvcHRpb25hbCBib29sIGFwcGx5X2hlcmUgPSAxIFtkZWZhdWx0ID0gdHJ1ZV07CgkJLy8gVHJ1ZSBpZiB0aGlzIEFDTCBhcHBsaWVzIHRvIHRoZSBzdWIgY2hhbm5lbHMuCgkJb3B0aW9uYWwgYm9vbCBhcHBseV9zdWJzID0gMiBbZGVmYXVsdCA9IHRydWVdOwoJCS8vIFRydWUgaWYgdGhlIEFDTCBoYXMgYmVlbiBpbmhlcml0ZWQgZnJvbSB0aGUgcGFyZW50LgoJCW9wdGlvbmFsIGJvb2wgaW5oZXJpdGVkID0gMyBbZGVmYXVsdCA9IHRydWVdOwoJCS8vIElEIG9mIHRoZSB1c2VyIHRoYXQgaXMgYWZmZWN0ZWQgYnkgdGhpcyBBQ0wuCgkJb3B0aW9uYWwgdWludDMyIHVzZXJfaWQgPSA0OwoJCS8vIElEIG9mIHRoZSBncm91cCB0aGF0IGlzIGFmZmVjdGVkIGJ5IHRoaXMgQUNMLgoJCW9wdGlvbmFsIHN0cmluZyBncm91cCA9IDU7CgkJLy8gQml0IGZsYWcgZmllbGQgb2YgdGhlIHBlcm1pc3Npb25zIGdyYW50ZWQgYnkgdGhpcyBBQ0wuCgkJb3B0aW9uYWwgdWludDMyIGdyYW50ID0gNjsKCQkvLyBCaXQgZmxhZyBmaWVsZCBvZiB0aGUgcGVybWlzc2lvbnMgZGVuaWVkIGJ5IHRoaXMgQUNMLgoJCW9wdGlvbmFsIHVpbnQzMiBkZW55ID0gNzsKCX0KCS8vIENoYW5uZWwgSUQgb2YgdGhlIGNoYW5uZWwgdGhpcyBtZXNzYWdlIGFmZmVjdHMuCglyZXF1aXJlZCB1aW50MzIgY2hhbm5lbF9pZCA9IDE7CgkvLyBUcnVlIGlmIHRoZSBjaGFubmVsIGluaGVyaXRzIGl0cyBwYXJlbnQncyBBQ0xzLgoJb3B0aW9uYWwgYm9vbCBpbmhlcml0X2FjbHMgPSAyIFtkZWZhdWx0ID0gdHJ1ZV07CgkvLyBVc2VyIGdyb3VwIHNwZWNpZmljYXRpb25zLgoJcmVwZWF0ZWQgQ2hhbkdyb3VwIGdyb3VwcyA9IDM7CgkvLyBBQ0wgc3BlY2lmaWNhdGlvbnMuCglyZXBlYXRlZCBDaGFuQUNMIGFjbHMgPSA0OwoJLy8gVHJ1ZSBpZiB0aGUgbWVzc2FnZSBpcyBhIHF1ZXJ5IGZvciBBQ0xzIGluc3RlYWQgb2Ygc2V0dGluZyB0aGVtLgoJb3B0aW9uYWwgYm9vbCBxdWVyeSA9IDUgW2RlZmF1bHQgPSBmYWxzZV07Cn0KCi8vIENsaWVudCBtYXkgdXNlIHRoaXMgbWVzc2FnZSB0byByZWZyZXNoIGl0cyByZWdpc3RlcmVkIHVzZXIgaW5mb3JtYXRpb24uIFRoZQovLyBjbGllbnQgc2hvdWxkIGZpbGwgdGhlIElEcyBvciBOYW1lcyBvZiB0aGUgdXNlcnMgaXQgd2FudHMgdG8gcmVmcmVzaC4gVGhlCi8vIHNlcnZlciBmaWxscyB0aGUgbWlzc2luZyBwYXJ0cyBhbmQgc2VuZHMgdGhlIG1lc3NhZ2UgYmFjay4KbWVzc2FnZSBRdWVyeVVzZXJzIHsKCS8vIHVzZXJfaWRzLgoJcmVwZWF0ZWQgdWludDMyIGlkcyA9IDE7CgkvLyBVc2VyIG5hbWVzIGluIHRoZSBzYW1lIG9yZGVyIGFzIGlkcy4KCXJlcGVhdGVkIHN0cmluZyBuYW1lcyA9IDI7Cn0KCi8vIFVzZWQgdG8gaW5pdGlhbGl6ZSBhbmQgcmVzeW5jIHRoZSBVRFAgZW5jcnlwdGlvbi4gRWl0aGVyIHNpZGUgbWF5IHJlcXVlc3QgYQovLyByZXN5bmMgYnkgc2VuZGluZyB0aGUgbWVzc2FnZSB3aXRob3V0IGFueSB2YWx1ZXMgZmlsbGVkLiBUaGUgcmVzeW5jIGlzCi8vIHBlcmZvcm1lZCBieSBzZW5kaW5nIHRoZSBtZXNzYWdlIHdpdGggb25seSB0aGUgY2xpZW50IG9yIHNlcnZlciBub25jZQovLyBmaWxsZWQuCm1lc3NhZ2UgQ3J5cHRTZXR1cCB7CgkvLyBFbmNyeXB0aW9uIGtleS4KCW9wdGlvbmFsIGJ5dGVzIGtleSA9IDE7CgkvLyBDbGllbnQgbm9uY2UuCglvcHRpb25hbCBieXRlcyBjbGllbnRfbm9uY2UgPSAyOwoJLy8gU2VydmVyIG5vbmNlLgoJb3B0aW9uYWwgYnl0ZXMgc2VydmVyX25vbmNlID0gMzsKfQoKbWVzc2FnZSBDb250ZXh0QWN0aW9uTW9kaWZ5IHsKCWVudW0gQ29udGV4dCB7CgkJLy8gQWN0aW9uIGlzIGFwcGxpY2FibGUgdG8gdGhlIHNlcnZlci4KCQlTZXJ2ZXIgPSAweDAxOwoJCS8vIEFjdGlvbiBjYW4gdGFyZ2V0IGEgQ2hhbm5lbC4KCQlDaGFubmVsID0gMHgwMjsKCQkvLyBBY3Rpb24gY2FuIHRhcmdldCBhIFVzZXIuCgkJVXNlciA9IDB4MDQ7Cgl9CgllbnVtIE9wZXJhdGlvbiB7CgkJQWRkID0gMDsKCQlSZW1vdmUgPSAxOwoJfQoJLy8gVGhlIGFjdGlvbiBuYW1lLgoJcmVxdWlyZWQgc3RyaW5nIGFjdGlvbiA9IDE7CgkvLyBUaGUgZGlzcGxheSBuYW1lIG9mIHRoZSBhY3Rpb24uCglvcHRpb25hbCBzdHJpbmcgdGV4dCA9IDI7CgkvLyBDb250ZXh0IGJpdCBmbGFncyBkZWZpbmluZyB3aGVyZSB0aGUgYWN0aW9uIHNob3VsZCBiZSBkaXNwbGF5ZWQuCglvcHRpb25hbCB1aW50MzIgY29udGV4dCA9IDM7CglvcHRpb25hbCBPcGVyYXRpb24gb3BlcmF0aW9uID0gNDsKfQoKLy8gU2VudCBieSB0aGUgY2xpZW50IHdoZW4gaXQgd2FudHMgdG8gaW5pdGlhdGUgYSBDb250ZXh0IGFjdGlvbi4KbWVzc2FnZSBDb250ZXh0QWN0aW9uIHsKCS8vIFRoZSB0YXJnZXQgVXNlciBmb3IgdGhlIGFjdGlvbiwgaWRlbnRpZmllZCBieSBzZXNzaW9uLgoJb3B0aW9uYWwgdWludDMyIHNlc3Npb24gPSAxOwoJLy8gVGhlIHRhcmdldCBDaGFubmVsIGZvciB0aGUgYWN0aW9uLCBpZGVudGlmaWVkIGJ5IGNoYW5uZWxfaWQuCglvcHRpb25hbCB1aW50MzIgY2hhbm5lbF9pZCA9IDI7CgkvLyBUaGUgYWN0aW9uIHRoYXQgc2hvdWxkIGJlIGV4ZWN1dGVkLgoJcmVxdWlyZWQgc3RyaW5nIGFjdGlvbiA9IDM7Cn0KCi8vIExpc3RzIHRoZSByZWdpc3RlcmVkIHVzZXJzLgptZXNzYWdlIFVzZXJMaXN0IHsKCW1lc3NhZ2UgVXNlciB7CgkJLy8gUmVnaXN0ZXJlZCB1c2VyIElELgoJCXJlcXVpcmVkIHVpbnQzMiB1c2VyX2lkID0gMTsKCQkvLyBSZWdpc3RlcmVkIHVzZXIgbmFtZS4KCQlvcHRpb25hbCBzdHJpbmcgbmFtZSA9IDI7CgkJb3B0aW9uYWwgc3RyaW5nIGxhc3Rfc2VlbiA9IDM7CgkJb3B0aW9uYWwgdWludDMyIGxhc3RfY2hhbm5lbCA9IDQ7Cgl9CgkvLyBBIGxpc3Qgb2YgcmVnaXN0ZXJlZCB1c2Vycy4KCXJlcGVhdGVkIFVzZXIgdXNlcnMgPSAxOwp9CgovLyBTZW50IGJ5IHRoZSBjbGllbnQgd2hlbiBpdCB3YW50cyB0byByZWdpc3RlciBvciBjbGVhciB3aGlzcGVyIHRhcmdldHMuCi8vCi8vIE5vdGU6IFRoZSBmaXJzdCBhdmFpbGFibGUgdGFyZ2V0IElEIGlzIDEgYXMgMCBpcyByZXNlcnZlZCBmb3Igbm9ybWFsCi8vIHRhbGtpbmcuIE1heGltdW0gdGFyZ2V0IElEIGlzIDMwLgptZXNzYWdlIFZvaWNlVGFyZ2V0IHsKCW1lc3NhZ2UgVGFyZ2V0IHsKCQkvLyBVc2VycyB0aGF0IGFyZSBpbmNsdWRlZCBhcyB0YXJnZXRzLgoJCXJlcGVhdGVkIHVpbnQzMiBzZXNzaW9uID0gMTsKCQkvLyBDaGFubmVsIHRoYXQgaXMgaW5jbHVkZWQgYXMgYSB0YXJnZXQuCgkJb3B0aW9uYWwgdWludDMyIGNoYW5uZWxfaWQgPSAyOwoJCS8vIEFDTCBncm91cCB0aGF0IGlzIGluY2x1ZGVkIGFzIGEgdGFyZ2V0LgoJCW9wdGlvbmFsIHN0cmluZyBncm91cCA9IDM7CgkJLy8gVHJ1ZSBpZiB0aGUgdm9pY2Ugc2hvdWxkIGZvbGxvdyBsaW5rcyBmcm9tIHRoZSBzcGVjaWZpZWQgY2hhbm5lbC4KCQlvcHRpb25hbCBib29sIGxpbmtzID0gNCBbZGVmYXVsdCA9IGZhbHNlXTsKCQkvLyBUcnVlIGlmIHRoZSB2b2ljZSBzaG91bGQgYWxzbyBiZSBzZW50IHRvIGNoaWxkcmVuIG9mIHRoZSBzcGVjaWZpYwoJCS8vIGNoYW5uZWwuCgkJb3B0aW9uYWwgYm9vbCBjaGlsZHJlbiA9IDUgW2RlZmF1bHQgPSBmYWxzZV07Cgl9CgkvLyBWb2ljZSB0YXJnZXQgSUQuCglvcHRpb25hbCB1aW50MzIgaWQgPSAxOwoJLy8gVGhlIHJlY2VpdmVycyB0aGF0IHRoaXMgdm9pY2UgdGFyZ2V0IGluY2x1ZGVzLgoJcmVwZWF0ZWQgVGFyZ2V0IHRhcmdldHMgPSAyOwp9CgovLyBTZW50IGJ5IHRoZSBjbGllbnQgd2hlbiBpdCB3YW50cyBwZXJtaXNzaW9ucyBmb3IgYSBjZXJ0YWluIGNoYW5uZWwuIFNlbnQgYnkKLy8gdGhlIHNlcnZlciB3aGVuIGl0IHJlcGxpZXMgdG8gdGhlIHF1ZXJ5IG9yIHdhbnRzIHRoZSB1c2VyIHRvIHJlc3luYyBhbGwKLy8gY2hhbm5lbCBwZXJtaXNzaW9ucy4KbWVzc2FnZSBQZXJtaXNzaW9uUXVlcnkgewoJLy8gY2hhbm5lbF9pZCBvZiB0aGUgY2hhbm5lbCBmb3Igd2hpY2ggdGhlIHBlcm1pc3Npb25zIGFyZSBxdWVyaWVkLgoJb3B0aW9uYWwgdWludDMyIGNoYW5uZWxfaWQgPSAxOwoJLy8gQ2hhbm5lbCBwZXJtaXNzaW9ucy4KCW9wdGlvbmFsIHVpbnQzMiBwZXJtaXNzaW9ucyA9IDI7CgkvLyBUcnVlIGlmIHRoZSBjbGllbnQgc2hvdWxkIGRyb3AgaXRzIGN1cnJlbnQgcGVybWlzc2lvbiBpbmZvcm1hdGlvbiBmb3IgYWxsCgkvLyBjaGFubmVscy4KCW9wdGlvbmFsIGJvb2wgZmx1c2ggPSAzIFtkZWZhdWx0ID0gZmFsc2VdOwp9CgovLyBTZW50IGJ5IHRoZSBzZXJ2ZXIgdG8gbm90aWZ5IHRoZSB1c2VycyBvZiB0aGUgdmVyc2lvbiBvZiB0aGUgQ0VMVCBjb2RlYyB0aGV5Ci8vIHNob3VsZCB1c2UuIFRoaXMgbWF5IGNoYW5nZSBkdXJpbmcgdGhlIGNvbm5lY3Rpb24gd2hlbiBuZXcgdXNlcnMgam9pbi4KbWVzc2FnZSBDb2RlY1ZlcnNpb24gewoJLy8gVGhlIHZlcnNpb24gb2YgdGhlIENFTFQgQWxwaGEgY29kZWMuCglyZXF1aXJlZCBpbnQzMiBhbHBoYSA9IDE7CgkvLyBUaGUgdmVyc2lvbiBvZiB0aGUgQ0VMVCBCZXRhIGNvZGVjLgoJcmVxdWlyZWQgaW50MzIgYmV0YSA9IDI7CgkvLyBUcnVlIGlmIHRoZSB1c2VyIHNob3VsZCBwcmVmZXIgQWxwaGEgb3ZlciBCZXRhLgoJcmVxdWlyZWQgYm9vbCBwcmVmZXJfYWxwaGEgPSAzIFtkZWZhdWx0ID0gdHJ1ZV07CglvcHRpb25hbCBib29sIG9wdXMgPSA0IFtkZWZhdWx0ID0gZmFsc2VdOwp9CgovLyBVc2VkIHRvIGNvbW11bmljYXRlIHVzZXIgc3RhdHMgYmV0d2VlbiB0aGUgc2VydmVyIGFuZCBjbGllbnRzLgptZXNzYWdlIFVzZXJTdGF0cyB7CgltZXNzYWdlIFN0YXRzIHsKCQkvLyBUaGUgYW1vdW50IG9mIGdvb2QgcGFja2V0cyByZWNlaXZlZC4KCQlvcHRpb25hbCB1aW50MzIgZ29vZCA9IDE7CgkJLy8gVGhlIGFtb3VudCBvZiBsYXRlIHBhY2tldHMgcmVjZWl2ZWQuCgkJb3B0aW9uYWwgdWludDMyIGxhdGUgPSAyOwoJCS8vIFRoZSBhbW91bnQgb2YgcGFja2V0cyBuZXZlciByZWNlaXZlZC4KCQlvcHRpb25hbCB1aW50MzIgbG9zdCA9IDM7CgkJLy8gVGhlIGFtb3VudCBvZiBub25jZSByZXN5bmNzLgoJCW9wdGlvbmFsIHVpbnQzMiByZXN5bmMgPSA0OwoJfQoKCS8vIFVzZXIgd2hvc2Ugc3RhdHMgdGhlc2UgYXJlLgoJb3B0aW9uYWwgdWludDMyIHNlc3Npb24gPSAxOwoJLy8gVHJ1ZSBpZiB0aGUgbWVzc2FnZSBjb250YWlucyBvbmx5IG11dGFibGUgc3RhdHMgKHBhY2tldHMsIHBpbmcpLgoJb3B0aW9uYWwgYm9vbCBzdGF0c19vbmx5ID0gMiBbZGVmYXVsdCA9IGZhbHNlXTsKCS8vIEZ1bGwgdXNlciBjZXJ0aWZpY2F0ZSBjaGFpbiBvZiB0aGUgdXNlciBjZXJ0aWZpY2F0ZSBpbiBERVIgZm9ybWF0LgoJcmVwZWF0ZWQgYnl0ZXMgY2VydGlmaWNhdGVzID0gMzsKCS8vIFBhY2tldCBzdGF0aXN0aWNzIGZvciBwYWNrZXRzIHJlY2VpdmVkIGZyb20gdGhlIGNsaWVudC4KCW9wdGlvbmFsIFN0YXRzIGZyb21fY2xpZW50ID0gNDsKCS8vIFBhY2tldCBzdGF0aXN0aWNzIGZvciBwYWNrZXRzIHNlbnQgYnkgdGhlIHNlcnZlci4KCW9wdGlvbmFsIFN0YXRzIGZyb21fc2VydmVyID0gNTsKCgkvLyBBbW91bnQgb2YgVURQIHBhY2tldHMgc2VudC4KCW9wdGlvbmFsIHVpbnQzMiB1ZHBfcGFja2V0cyA9IDY7CgkvLyBBbW91bnQgb2YgVENQIHBhY2tldHMgc2VudC4KCW9wdGlvbmFsIHVpbnQzMiB0Y3BfcGFja2V0cyA9IDc7CgkvLyBVRFAgcGluZyBhdmVyYWdlLgoJb3B0aW9uYWwgZmxvYXQgdWRwX3BpbmdfYXZnID0gODsKCS8vIFVEUCBwaW5nIHZhcmlhbmNlLgoJb3B0aW9uYWwgZmxvYXQgdWRwX3BpbmdfdmFyID0gOTsKCS8vIFRDUCBwaW5nIGF2ZXJhZ2UuCglvcHRpb25hbCBmbG9hdCB0Y3BfcGluZ19hdmcgPSAxMDsKCS8vIFRDUCBwaW5nIHZhcmlhbmNlLgoJb3B0aW9uYWwgZmxvYXQgdGNwX3BpbmdfdmFyID0gMTE7CgoJLy8gQ2xpZW50IHZlcnNpb24uCglvcHRpb25hbCBWZXJzaW9uIHZlcnNpb24gPSAxMjsKCS8vIEEgbGlzdCBvZiBDRUxUIGJpdHN0cmVhbSB2ZXJzaW9uIGNvbnN0YW50cyBzdXBwb3J0ZWQgYnkgdGhlIGNsaWVudCBvZiB0aGlzCgkvLyB1c2VyLgoJcmVwZWF0ZWQgaW50MzIgY2VsdF92ZXJzaW9ucyA9IDEzOwoJLy8gQ2xpZW50IElQIGFkZHJlc3MuCglvcHRpb25hbCBieXRlcyBhZGRyZXNzID0gMTQ7CgkvLyBCYW5kd2l0aCB1c2VkIGJ5IHRoaXMgY2xpZW50LgoJb3B0aW9uYWwgdWludDMyIGJhbmR3aWR0aCA9IDE1OwoJLy8gQ29ubmVjdGlvbiBkdXJhdGlvbi4KCW9wdGlvbmFsIHVpbnQzMiBvbmxpbmVzZWNzID0gMTY7CgkvLyBEdXJhdGlvbiBzaW5jZSBsYXN0IGFjdGl2aXR5LgoJb3B0aW9uYWwgdWludDMyIGlkbGVzZWNzID0gMTc7CgkvLyBUcnVlIGlmIHRoZSB1c2VyIGhhcyBhIHN0cm9uZyBjZXJ0aWZpY2F0ZS4KCW9wdGlvbmFsIGJvb2wgc3Ryb25nX2NlcnRpZmljYXRlID0gMTggW2RlZmF1bHQgPSBmYWxzZV07CglvcHRpb25hbCBib29sIG9wdXMgPSAxOSBbZGVmYXVsdCA9IGZhbHNlXTsKfQoKLy8gVXNlZCBieSB0aGUgY2xpZW50IHRvIHJlcXVlc3QgYmluYXJ5IGRhdGEgZnJvbSB0aGUgc2VydmVyLiBCeSBkZWZhdWx0IGxhcmdlCi8vIGNvbW1lbnRzIG9yIHRleHR1cmVzIGFyZSBub3Qgc2VudCB3aXRoaW4gc3RhbmRhcmQgbWVzc2FnZXMgYnV0IGluc3RlYWQgdGhlCi8vIGhhc2ggaXMuIElmIHRoZSBjbGllbnQgZG9lcyBub3QgcmVjb2duaXplIHRoZSBoYXNoIGl0IG1heSByZXF1ZXN0IHRoZQovLyByZXNvdXJjZSB3aGVuIGl0IG5lZWRzIGl0LiBUaGUgY2xpZW50IGRvZXMgc28gYnkgc2VuZGluZyBhIFJlcXVlc3RCbG9iCi8vIG1lc3NhZ2Ugd2l0aCB0aGUgY29ycmVjdCBmaWVsZHMgZmlsbGVkIHdpdGggdGhlIHVzZXIgc2Vzc2lvbnMgb3IgY2hhbm5lbF9pZHMKLy8gaXQgd2FudHMgdG8gcmVjZWl2ZS4gVGhlIHNlcnZlciByZXBsaWVzIHRvIHRoaXMgYnkgc2VuZGluZyBhIG5ldwovLyBVc2VyU3RhdGUvQ2hhbm5lbFN0YXRlIG1lc3NhZ2Ugd2l0aCB0aGUgcmVzb3VyY2VzIGZpbGxlZCBldmVuIGlmIHRoZXkgd291bGQKLy8gbm9ybWFsbHkgYmUgdHJhbnNtaXR0ZWQgYXMgaGFzaGVzLgptZXNzYWdlIFJlcXVlc3RCbG9iIHsKCS8vIHNlc3Npb25zIG9mIHRoZSByZXF1ZXN0ZWQgVXNlclN0YXRlIHRleHR1cmVzLgoJcmVwZWF0ZWQgdWludDMyIHNlc3Npb25fdGV4dHVyZSA9IDE7CgkvLyBzZXNzaW9ucyBvZiB0aGUgcmVxdWVzdGVkIFVzZXJTdGF0ZSBjb21tZW50cy4KCXJlcGVhdGVkIHVpbnQzMiBzZXNzaW9uX2NvbW1lbnQgPSAyOwoJLy8gY2hhbm5lbF9pZHMgb2YgdGhlIHJlcXVlc3RlZCBDaGFubmVsU3RhdGUgZGVzY3JpcHRpb25zLgoJcmVwZWF0ZWQgdWludDMyIGNoYW5uZWxfZGVzY3JpcHRpb24gPSAzOwp9CgovLyBTZW50IGJ5IHRoZSBzZXJ2ZXIgd2hlbiBpdCBpbmZvcm1zIHRoZSBjbGllbnRzIG9uIHNlcnZlciBjb25maWd1cmF0aW9uCi8vIGRldGFpbHMuCm1lc3NhZ2UgU2VydmVyQ29uZmlnIHsKCS8vIFRoZSBtYXhpbXVtIGJhbmR3aWR0aCB0aGUgY2xpZW50cyBzaG91bGQgdXNlLgoJb3B0aW9uYWwgdWludDMyIG1heF9iYW5kd2lkdGggPSAxOwoJLy8gU2VydmVyIHdlbGNvbWUgdGV4dC4KCW9wdGlvbmFsIHN0cmluZyB3ZWxjb21lX3RleHQgPSAyOwoJLy8gVHJ1ZSBpZiB0aGUgc2VydmVyIGFsbG93cyBIVE1MLgoJb3B0aW9uYWwgYm9vbCBhbGxvd19odG1sID0gMzsKCS8vIE1heGltdW0gdGV4dCBtZXNzYWdlIGxlbmd0aC4KCW9wdGlvbmFsIHVpbnQzMiBtZXNzYWdlX2xlbmd0aCA9IDQ7CgkvLyBNYXhpbXVtIGltYWdlIG1lc3NhZ2UgbGVuZ3RoLgoJb3B0aW9uYWwgdWludDMyIGltYWdlX21lc3NhZ2VfbGVuZ3RoID0gNTsKCS8vIFRoZSBtYXhpbXVtIG51bWJlciBvZiB1c2VycyBhbGxvd2VkIG9uIHRoZSBzZXJ2ZXIuCglvcHRpb25hbCB1aW50MzIgbWF4X3VzZXJzID0gNjsKfQoKLy8gU2VudCBieSB0aGUgc2VydmVyIHRvIGluZm9ybSB0aGUgY2xpZW50cyBvZiBzdWdnZXN0ZWQgY2xpZW50IGNvbmZpZ3VyYXRpb24KLy8gc3BlY2lmaWVkIGJ5IHRoZSBzZXJ2ZXIgYWRtaW5pc3RyYXRvci4KbWVzc2FnZSBTdWdnZXN0Q29uZmlnIHsKCS8vIFN1Z2dlc3RlZCBjbGllbnQgdmVyc2lvbi4KCW9wdGlvbmFsIHVpbnQzMiB2ZXJzaW9uID0gMTsKCS8vIFRydWUgaWYgdGhlIGFkbWluaXN0cmF0b3Igc3VnZ2VzdHMgcG9zaXRpb25hbCBhdWRpbyB0byBiZSB1c2VkIG9uIHRoaXMKCS8vIHNlcnZlci4KCW9wdGlvbmFsIGJvb2wgcG9zaXRpb25hbCA9IDI7CgkvLyBUcnVlIGlmIHRoZSBhZG1pbmlzdHJhdG9yIHN1Z2dlc3RzIHB1c2ggdG8gdGFsayB0byBiZSB1c2VkIG9uIHRoaXMgc2VydmVyLgoJb3B0aW9uYWwgYm9vbCBwdXNoX3RvX3RhbGsgPSAzOwp9Cg==","base64");
var messages = protobufjs.loadProto(mumbleProto).build('MumbleProto');

/**
 * Encodes the given message.
 *
 * @param {string} name The name of the message.
 * @param {object} payload The message to be encoded.
 * @return {Buffer} The encoded message.
 */
function encode(name, payload) {
  var encoded = new messages[name](payload || {}).toBuffer();
  // toBuffer returns an ArrayBuffer when called in the browser
  if (!Buffer.isBuffer(encoded)) {
    encoded = Buffer.from(encoded);
  }
	return encoded;
}

/**
 * A message object.
 * @typedef {object} Message
 * @property {string} name - Name of the message
 * @property {object} [payload={}] - Payload of the message
 */

/**
 * Decodes the given message.
 *
 * @param {number} id The id of the message.
 * @param {Buffer} payload The encoded message.
 * @return {object} The decoded message.
 */
function decode(id, payload) {
	var name = nameById[id];
	return new messages[name].decode(payload || {});
}

/**
 * Transform stream for encoding {@link Message Mumble messages}.
 *
 * @constructor
 * @constructs Encoder
 */
function Encoder() {
  // Allow use without new
  if (!(this instanceof Encoder)) return new Encoder();

  Transform.call(this, {
    writableObjectMode: true
  });
}
util.inherits(Encoder, Transform);

Encoder.prototype._transform = function(chunk, encoding, callback) {
  if (typeof chunk.name !== 'string') {
    return callback(new TypeError('chunk.name is not a string'));
  }
  chunk.payload = chunk.payload || {};

  // First, encode the payload
  var data;
  if (chunk.name == 'UDPTunnel') {
    // UDPTunnel message doesn't need encoding
    data = chunk.payload;
  } else {
    try {
      // Encode the message payload
      data = encode(chunk.name, chunk.payload);
    } catch (e) {
      callback(e);
      return;
    }
  }

  // Then create the header
  var header = new Buffer(6);
  header.writeUInt16BE(idByName[chunk.name], 0);
  header.writeUInt32BE(data.length, 2);

  callback(null, Buffer.concat([header, data]));
};

/**
 * Transform stream for decoding {@link Message Mumble messages}.
 *
 * @constructor
 * @constructs Decoder
 */
function Decoder() {
  // Allow use without new
  if (!(this instanceof Decoder)) return new Decoder();

  Transform.call(this, {
    readableObjectMode: true
  });

	this._buffer = new Buffer(1024);
	this._bufferSize = 0;
}
util.inherits(Decoder, Transform);

Decoder.prototype._transform = function(chunk, encoding, callback) {
  // Add incoming chunk to internal buffer
	if (this._buffer.length - this._bufferSize < chunk.length) {
    // Old buffer is too small, replace with bigger one
		var oldBuffer = this._buffer;
		this._buffer = new Buffer(this._bufferSize + chunk.length);
		oldBuffer.copy(this._buffer, 0, 0, this._bufferSize);
	}
	this._bufferSize += chunk.copy(this._buffer, this._bufferSize);


  // Try to decode messages while we still have enough bytes
	while (this._bufferSize >= 6) {
		var type = this._buffer.readUInt16BE(0);
		var size = this._buffer.readUInt32BE(2);
		if (this._bufferSize < 6 + size) {
			break; // Not enough bytes in internal buffer for the expected payload
		}

		var typeName = nameById[type];
		var data = this._buffer.slice(6, 6 + size);
    // Decode payload
		var message;
    if (typeName == 'UDPTunnel') {
      // UDPTunnel payload is not encoded
		  message = new Buffer(data);
    } else {
      try {
		    message = decode(type, data);
      } catch (e) {
        return callback(e);
      }
    }

    // Shift remaining bytes to start of internal buffer
		this._buffer.copy(this._buffer, 0, 6 + size, this._bufferSize);
		this._bufferSize -= 6 + size;

    this.push({
      name: typeName,
      payload: message
    });
	}
  callback();
};

module.exports = {
  Encoder: Encoder,
  Decoder: Decoder,
  messages: messages
};